[package]
name = "seec-yamux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yamux = "0.13.1"
futures = "0.3.30"
tokio = { version = "1.36.0", features = ["macros", "sync"]}