language: cpp
compiler: g++
dist: bionic

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: 'ppa:mhier/libboost-latest'

before_install:
  - sudo add-apt-repository -y ppa:mhier/libboost-latest
  - sudo apt-get update
  - sudo apt-get install -y g++-10 libboost1.74-dev libgmp-dev libssl-dev
  # Install a recent CMake
  - mkdir $HOME/prefix
  - export PATH="$HOME/prefix/bin:$PATH"
  - wget https://cmake.org/files/v3.19/cmake-3.19.5-Linux-x86_64.sh -O cmake_install.sh
  - chmod +x cmake_install.sh
  - ./cmake_install.sh --prefix=$HOME/prefix --exclude-subdir --skip-license

script:
  - mkdir build_debug
  - cd build_debug
  - CC=/usr/bin/gcc-10 CXX=/usr/bin/g++-10 cmake -DCMAKE_BUILD_TYPE=Debug -DMOTION_BUILD_TESTS=On -j 2 ..
  - make -j 2
  # travis does not support IPv6 ...
  - ./bin/motiontest --gtest_filter='-*ipv6*'

notifications:
  - email: false
