language: cpp
compiler: g++
dist: bionic

before_install:
  - sudo add-apt-repository -y ppa:mhier/libboost-latest
  - sudo apt-get update
  - sudo apt-get install -y g++-8 libboost1.70-dev libgmp-dev libssl-dev
  # Install a recent CMake
  - mkdir $HOME/prefix
  - export PATH="$HOME/prefix/bin:$PATH"
  - wget https://cmake.org/files/v3.15/cmake-3.15.1-Linux-x86_64.sh -O cmake_install.sh
  - chmod +x cmake_install.sh
  - ./cmake_install.sh --prefix=$HOME/prefix --exclude-subdir --skip-license

script:
  - mkdir build_debug
  - cd build_debug
  - CC=/usr/bin/gcc-8 CXX=/usr/bin/g++-8 cmake .. -DCMAKE_BUILD_TYPE=Debug -DABY_BUILD_EXE=On
  - make -j 2
  - ./bin/abytest -r 0 -q &
  - ./bin/abytest -r 1 -q

notifications:
  - email: false
